import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import '@ant-design/v5-patch-for-react-19';


export const metadata: Metadata = {
  title: "FEEDO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          padding: 0,
          fontFamily: "Arial, sans-serif",
          backgroundColor: "#f5f5f5",
          }}>
        <AppRouterCacheProvider>
          <AntdRegistry>{children}</AntdRegistry>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
